### PR TITLE
Remove unused `_helper` method

### PR DESCRIPTION
**Pull request by caillou**
It seems like the `_helper` method has no reason to be. Instead we can just call `SuperClass.apply(this, {})`.

### CODE REVIEW

**Comment by backflip** [comment]
Thanks for the input! We are currently preparing an ES2015 version and will push it in the next days, so this will most probably be superseded by a "real" Class approach. I will keep you posted.

**Comment by caillou** [comment]
@backflip ok. Just to be sure: this is some legacy code, right? Or is there a reason for the `_helper()`? I plan to do a refactoring on our codebase ;)

**Comment by backflip** [comment]
There might have been a reason at one point. Though I can't really think of one right now.

**Comment by caillou** [comment]
@backflip could you either merge or close the PR?

**Pull request closed without merging**
