### PR TITLE
updated gulp-hb to the latest versions

### PR DESCRIPTION
**Pull request by swey**
Solves the problems with `@root`, fixes the problems of #36

### CODE REVIEW

**Comment by backflip** [comment]
@swey, do we have to update any gulp tasks since the API seems to have changed a bit?

**Comment by swey** [comment]
At least I did not figure out any broken things - only the fixed one.

The option `dataEach` was deprecated in 5.1.4, maybe this option should be removed. Please double check it.

**Comment by backflip** [comment]
image

**Comment by backflip** [comment]
Okay, we can remove `dataEach` from `html/default.js` and `bustCache` from every file (seems to default to `true`): https://github.com/unic/estatico/pull/42

**Pull request closed without merging**
