### PR TITLE
gulp scaffold: fix issues and improve

### PR DESCRIPTION
**Pull request by tschuems**
Like @backflip said in #15 
fix issues with JS class name

prettify scaffolding by adding new variables. 
now you can choose between camelCased-, pascalCased-, original- and lowerCased-Name.

the camelCased name can be used i.e. for the initialisation of react modules.

### CODE REVIEW

**Comment by orioltf** [comment]
Isn't it needed to patch *.data.js modules files too? I specially mean it for scaffold:rename, scaffold:copy and scaffold:delete to work. At least this was my experience when adapting scaffold for React.

**Comment by tschuems** [comment]
i don't think so
it could be if you have some additional module types

**Comment by backflip** [comment]
We will need automated tests at one point (I have started with this already). But for now, I'd be fine with manual (i.e. "works on my machine") tests.

**Comment by orioltf** [comment]
- `gulp scaffold:delete`> `modules` > `all` fails because of the use of `_.pluck` => We should merge #27 in here to solve this.
- `gulp scaffold:delete`> `modules` > `all` fails. This may have to do with missing attributes in the `*.data.js` files.

**Comment by lbsonley** [comment]
This pull request looks good to me.

`gulp scaffold:delete` > `Demo Pages` > `* (all)` only fails when you run `gulp scaffold:delete` > `Demo Modules` > `* (all)` first

this is due to a `requireNew` in the pages data files pointing to one of the demo modules

So... when removing the demo modules and pages, make sure to remove the pages first and everything will work

**Pull request merged**
