### PR TITLE
[WIP] Add Stylelint

### PR DESCRIPTION
**Pull request by backflip**
- [ ] Document config (I basically started with the defaults and adapted them wherever I thought our somewhat implicit guidelines would expect something different)
- [ ] Fix watcher (it won't run as a dependency of `css` when the file watcher is triggering the task function directly: https://github.com/unic/estatico/blob/develop/gulp/watch.js#L41). This currently fails for JS linting, too, I assume.
- [x] Use default notification handling on errors (it currently doesn't trigger a OS X notification, e.g.)
- [ ] Test in IDEs
- [ ] Discuss!!

### CODE REVIEW

**Comment by lbsonley** [comment]
Stylelint is not a very effective tool in Webstorm. Errors are not displayed in a usable way.

screen shot 2017-02-10 at 16 33 17

**Comment by backflip** [comment]
Let's wait until WebStorm displays errors in a more meaningful way.

**Comment by orioltf** [comment]
Could we re-check the status from this PR? We need to go forward with the BEM implementation and I guess Stylelint could help with it, right?  I see some options with this according to https://www.smashingmagazine.com/2016/05/stylelint-the-style-sheet-linter-weve-always-wanted/, but googling around I ca see a [postcss linter](https://github.com/postcss/postcss-bem-linter) and a [Stylint plugin](https://github.com/davidtheclark/stylelint-selector-bem-pattern) that incorporates the previous.

There is even [BEMLint](https://www.npmjs.com/package/bemlint) that checks HTML files too. Would it work with hbs files? (Sounds like a challenge to take! 😜

@lbsonley Would you like / Would you have time to invest some in it?
@backflip How would you see this?

**Comment by lbsonley** [comment]
@orioltf 
I will take a look a this again over the weekend.

**Comment by backflip** [comment]
Added to [new implementation](https://github.com/unic/estatico-nou/tree/master/packages/estatico-stylelint), currently waiting for proper configuration: https://github.com/unic/estatico-nou/issues/6

**Pull request closed without merging**
